version: "3"
services: 
  redis:
    image: "redis"
    ports:
     - "6379:6379"
  app:
    build: .
    command: npm run dev
    volumes: 
      - .:/usr/app
    ports: 
      - "3000:3000"
      - "9229:9229"
    env_file: 
      - ./app.env
    